name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm run ng -- deploy --repo="https://github.com/laura-chou/angular_LDmart.git" --base-href=/angular_LDmart/ --name=developer --email=develop@gmail.com
